### ISSUE TITLE
New update broke compatibility with Firefox via Chrome Store Foxified

### ISSUE THREAD

**Issue by wonglkd** [wonglkd/mathflowy#4]
> @wonglkd Thank you for the fix. Just one thing … the old version could be used in Firefox as well, via the extension "Chrome Store Foxified". Since the update, this doesn't work anymore (installing the extension has no effect whatsoever).
> 
> I'm aware that Mathflowy is a Chrome extension and that it is not your responsibility to maintain compatibility with another browser via a third-party extension – but if you could do anything about this, it would be great. (Actually, I think it was not the fix of this issue that broke Firefox support but the additional settings that were added in the subsequent commit.)

**Comment by ClaudiusL** [comment]
It seems like commit dfa3f0376f64950ce391df28420aa9bc5443dc55 broke the compatibility with Firefox via Chrome Store Foxified. However, it is possible to use commit 81c87f05863b2a30cdd50eef5f2563ffe92f37a4 in Firefox (though without the comfort of Chrome Store Foxified):
- You need an account at [addons.mozilla.org](https://addons.mozilla.org)
- Download Mathflowy, version 81c87f05863b2a30cdd50eef5f2563ffe92f37a4
- Edit `manifest.json`: Modify `name` and `short_name` as you like. They should somehow indicate that this is a (kind of) fork. (Otherwise, the add-on could be confused with the version from the Chrome store installed via Chrome Store Foxified. But by the way, uninstall that one first.)
- Create a `zip` archive and add the two `js` files, the `png` files and  `manifest.json`.
- Change the extension of the archive to `xpi`.
- Go to [addons.mozilla.org](https://addons.mozilla.org), log in, and then click on "Tools --> Submit a New Add-on".
- Check "Do not list my add-on on this site" and upload the `xpi` file. (Make sure the checkbox is actually [still] checked.)
- "Continue" as many times as necessary.
- Click on the download link provided and then on the `xpi` file. This will install the (now signed) add-on.
- Reload Workflowy, in case the tab was open all the time.

Happy Mathflowy-ing!

**Comment by wonglkd** [comment]
Thanks for the detailed steps! The problem appears to be caused by Firefox not supporting the sync storage area (as documented in https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities).

Thankfully the fix appears to be quite easy. I've pushed a new commit 326ce69, which falls back to the local storage area. I loaded it in Firefox and it appears to work. (Steps: download [a zip of the repository](https://github.com/wonglkd/mathflowy/archive/master.zip), unzip it and load the manifest file in the directory via Load Temporary Add-on in `about:debugging`). If you could have a go at it, that would be great. I'll update the Chrome store version shortly.

Thanks for bringing this up!

**Comment by ClaudiusL** [comment]
Yep, this works, even the custom delimiters can be used in Firefox.

**Comment by wonglkd** [comment]
Thanks! Closing this issue since it's been fixed.
