### ISSUE TITLE
An option for keeping bullets rendered until edited?

### ISSUE THREAD

**Issue by aneuhold** [wonglkd/mathflowy#6]
When clicking on notes and bullets, rendering for latex goes away seemingly because it is rendered until clicked so you can edit it. 

In another extension called "Workflowy code formatter" it keeps the text rendered until the bullet is actually edited with some kind of character input, or deletion. This allows notes to contain rendered text and still be seen when opened. Could this be done with mathflowy?

**Comment by wonglkd** [comment]
Thanks for highlighting that extension to me! That's new to me. I've looked at [Workflowy code formatter](https://github.com/ryanpcmcquen/workflowyCodeFormatter/blob/master/workflowyCodeFormatter.js).

It seems that this might not translate directly over to Mathflowy though - in the other extension, the underlying code is still seen by the user, whereas with Mathflowy the LaTeX is hidden and replaced with the rendered LaTeX. From the user's perspective, how do you envision this working, since the input field is hidden and thus there would be no place for a cursor? Also, how would this work for someone using Workflowy with only the keyboard? (With Mathflowy, the derendering is triggered when the bullet is focused which includes navigation to it say from the previous/subsequent bullet.)

**Comment by aneuhold** [comment]
It seems that there must be some event that is triggered when text is actually edited in a bullet for rendering to change. Maybe the `focusin()` event from [workflowyCodeFormatter.js](https://github.com/ryanpcmcquen/workflowyCodeFormatter/blob/master/workflowyCodeFormatter.js)? With how MathJax maintains proper spacing between lines when using inline equations even with big symbols like summations, and because the rendered text seems to be copy and pastable on the mathjax website it seems that it could be held in place properly from the user perspective until the user decides to edit the bullet. When a bullet is edited with the code formatter extension most of the spacing changes which is a little jarring, but really well worth the result of having formatted text in notes. Plus you can highlight then copy and paste code too. 

I don't know very much about JavaScript, honestly none at all. Haha, so feel free to close the issue if this isn't possible. Your extension has been incredibly helpful through school and contributed greatly to the good grades I've gotten in the past 3 classes haha.
